name: 'Create a new comment'
description: 'Creates a comment for a new issue'
author: 'jonah jackson'

# Define your inputs here.
inputs:
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  node_id:
    description: 'The id of the node to add a comment to'
    required: true
  # label_status:
  #   description: 'The status of the set-label step'
  #   required: true
  # branch_status:
  #   description: 'The status of the create-linked-branch step'
  #   required: true
  # pr_status:
  #   description: 'The status of the create-pr step'
  #   required: true

runs:
  using: node20
  main: dist/index.js
