name: 'Sets the status of a project card'
description: 'Adds the specified label to the specified issue'
author: 'jonah jackson'

# Define your inputs here.
inputs:
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  issue_id:
    description: 'The id of the issue'
    required: true
  set_status_to:
    description: 'The name of the status to set the linked project card of the issue'
    required: true
  project_number:
    description: 'The number of the project to set the project card status in'
    required: true

runs:
  using: node20
  main: dist/index.js
