name: 'Set issue label'
description: 'Adds the specified label to the specified issue'
author: 'jonah jackson'

# Define your inputs here.
inputs:
 owner:
  description: 'The owner of the repository'
  required: true
 repo:
  description: 'The name of the repository'
  required: true
 issue_id:
  description: 'The id of the issue'
  required: true
 label:
  description: 'The desired label for the issue'
  required: true
 token:
  description: 'The token to use to access the GitHub API'
  required: true

runs:
 using: node20
 main: dist/index.js
