# https://docs.github.com/en/actions/learn-github-actions/contexts
# https://docs.github.com/en/webhooks/webhook-events-and-payloads
# https://github.com/alex-page/github-project-automation-plus
# https://github.com/actions/add-to-project
# https://docs.github.com/en/rest/overview/github-event-types?apiVersion=2022-11-28#issuesevent
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

name: Init new issue tickets
run-name: New feature - ${{github.event.issue.title}}

on:
 issues:
  types: [opened]

jobs:
 init-issue:
  runs-on: ubuntu-latest
  name: initialize new issue ticket
  steps:
   - name: Checkout
     id: checkout
     uses: actions/checkout@v4

   - name: set label on issue
     id: set-issue-label
     uses: ./set-issue-label
     with:
      token: ${{ secrets.GITHUB_TOKEN }}
      owner: ${{ github.repository_owner }}
      repo: ${{ github.event.repository.name }}
      issue_id: ${{ github.event.issue.node_id }}
      label: 'test'

   - name: create a linked branch
     id: create-linked-branch
     uses: ./create-linked-branch
     with:
      token: ${{ secrets.GITHUB_TOKEN }}
      owner: ${{ github.repository_owner }}
      repo: ${{ github.event.repository.name }}
      repo_id: ${{ github.event.repository.node_id }}
      issue_id: ${{ github.event.issue.node_id }}
      issue_title: ${{ github.event.issue.title }}
      branch_to_copy: 'main'

   - name: create a pull request
     id: create-pr
     uses: ./create-pr
     with:
      token: ${{ secrets.GITHUB_TOKEN }}
      repo_id: ${{ github.event.repository.node_id }}
      issue_title: ${{ github.event.issue.title }}
      merge_into_branch: 'development'

   - name: Print Output
     id: output
     run: echo "completed function call"
