# https://docs.github.com/en/actions/learn-github-actions/contexts
# https://docs.github.com/en/webhooks/webhook-events-and-payloads
# https://github.com/alex-page/github-project-automation-plus
# https://github.com/actions/add-to-project
# https://docs.github.com/en/rest/overview/github-event-types?apiVersion=2022-11-28#issuesevent
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

# vars is repository variables
# env is environment variables
# no idea how to call organization variables

name: Init new issue tickets
run-name: New issue - ${{github.event.issue.title}}

on:
  issues:
    types: [opened]

jobs:
  init-issue:
    runs-on: ubuntu-latest
    name: initialize new issue ticket
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: set label on issue
        id: set-issue-label
        uses: ./set-issue-label
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_id: ${{ github.event.repository.node_id }}
          issue_id: ${{ github.event.issue.node_id }}
          label: 'test'

      - name: create a linked branch from an issue
        id: create-linked-branch
        uses: ./create-linked-branch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_id: ${{ github.event.repository.node_id }}
          issue_id: ${{ github.event.issue.node_id }}
          issue_title: ${{ github.event.issue.title }}
          branch_to_copy: 'main'

      - name: create a pull request from a branch
        id: create-pr
        if: steps.create-linked-branch.outcome == 'success'
        uses: ./create-pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_id: ${{ github.event.repository.node_id }}
          pr_title: 'New feature - ${{ github.event.issue.title }}'
          merge_from_branch: ${{steps.create-linked-branch.outputs.linkedBranchName}} # derived from the create linked branch action -- must be exact
          merge_into_branch: 'development'

      - name: change the status of a linked project card by an issue
        id: set-status
        uses: ./set-status
        with:
          token: ${{ secrets.ORGANIZATION_PAT }}
          issue_id: ${{ github.event.issue.node_id }}
          set_status_to: 'In Development'

      - name: mention the pr on the issue
        id: create-comment-on-issue
        if: steps.create-pr.outcome == 'success'
        uses: ./create-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node_id: ${{ github.event.issue.node_id }}
          message: 'Linked to pull request: #${{steps.create-pr.outputs.prNum}}'

      - name: Print Output
        id: output
        run: echo "completed function call"
